### PR TITLE
explicitly load BAS namespace when retrieving object from state

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1263

### CODE REVIEW

**Comment by vandenman** [comment]
@AlexanderLyNL Any update on the review?

**Comment by AlexanderLyNL** [comment]
Hi Don,

I just checked this and it seems to fix https://github.com/jasp-stats/INTERNAL-jasp/issues/1263. Thanks. 

Cheers,
Alexander

**Review by AlexanderLyNL — APPROVED** [review]
Could this by the way cause a namespace clash?

**Comment by vandenman** [comment]
> Could this by the way cause a namespace clash?

Nope, unless other packages define methods with the postfix .bas

**Pull request merged**
