### PR TITLE
added bayesian logistic regression

### PR DESCRIPTION
**Pull request by fqixiang**
This is the skeleton for the bayesian logistic regression.
The code is mostly adapted from the existing bayesian linear regression module.
The major adaptation is the ability of the module to cope with factors, which the bayesian linear regression module cannot.

I'm no expert in Bayesian statistics, so I'm not sure if the model results make sense. Lots of testing required, unfortunately I can't do it on my own because I can't load jasp modules on JASP and the generated figures do not get displayed in R either.
Also, no unit test is prepared yet. If there's any recommendation, that'd be great!

### CODE REVIEW

**Comment by Kucharssim** [comment]
I made some changes to the code to fix some little issues here and there.

Otherwise the analysis looks ok.

There is an issue in that whereas the analysis runs fine from JASP, it crashes in R when the line `BAS::bas.glm` is called. I cannot quite find out why it works in JASP but not R. Perhaps some of the environment issues? Any ideas @vandenman? Because of this I could not generate any unit tests.

One implementation issue that may require some change is the posterior coefficient summary when a categorial predictor is used:

Screenshot 2023-04-16 at 15 36 53

The table here is consistent in implementation with linear regression, but in there only continuous predictors are allowed - so for each predictor we get one coefficient. Here all the `facFive` predictor we get multiple coefficients. These have (obviously) the same inclusion prob. etc, because they correspond to the same factor - you only include all of them or none of them. Perhaps for this case we should collapse the rows and show only the incl. prob. for the predictors, not the coefficients? However then we would need to move the posterior distribution summary for each coefficient into a separate table. Any thoughts @vandenman ?

**Comment by vandenman** [comment]
I would prefer the same layout as the Bayesian ANOVAs:

image

So a separate column for Level and not only showing the variable name once. If there are no factors in the analysis, I would hide the Level column (the Bayesian ANOVAs actually don't hide the level column, but they should). I don't think this is a mandatory change though.


I don't have any ideas for the failure inside jaspTools but I think it's a bit too short before the release to fix that now. 


Should I review the code btw or just check the analysis in JASP?

**Comment by Kucharssim** [comment]
> I would prefer the same layout as the Bayesian ANOVAs:

That's a good idea. However that would make the output inconsistent with classical linear and logistic regression. We could do this for those, too, but I don't have time atm.

@EJWagenmakers suggested this morning to just add a footnote to the posterior summary table explaining that the inclusion probabilities of coefficients associated with a specific factor are not independent of each other, or something like that. I prefer this option atm if you don't mind too much?

> Should I review the code btw or just check the analysis in JASP?

I mainly assigned you here to get your opinion about the issues in the comment.

I did code review already based on which I made some changes to the code. There is some code duplication with linear regression that I told you about some time ago, but I did not have time to fix that. Otherwise I find the code in principle reasonable, but a second pair of eyes never hurt 😛 

It runs fine in JASP for me, I assume we would also test it thoroughly before release. So I don't think it's necessary for you to test it out now, unless you want to check that I did not miss some detail about the options/output that needs fixing.

**Review by Kucharssim — APPROVED** [review]
ok, I managed to fix the tests, so I added some very simplistic one.

Now we also display a footnote like this:
Screenshot 2023-04-17 at 20 42 05

If @vandenman does not object, this is fine to merge

**Review by vandenman — APPROVED** [review]

**Pull request merged**
