### PR TITLE
Update plot tests for R 4.1.0 and vdiffr 1.0.0

### PR DESCRIPTION
**Pull request by Kucharssim**
Part of https://github.com/jasp-stats/INTERNAL-jasp/issues/1408

### CODE REVIEW

**Comment by vandenman** [comment]
@Kucharssim can you confirm that CorrelationBayesianPairs does no longer have any figures? If yes, that's why the folder structure changed:
image

The rest looks fine to me!

**Comment by Kucharssim** [comment]
CorrelationBayesianPairs no longer exists as a separate analysis, so figures in this folder were already orphaned as there are no tests to be done. Not sure why they were not deleted already, I suspect no one bothered to clean up. But maybe @AlexanderLyNL wanted to keep the figures for some reason?

**Comment by AlexanderLyNL** [comment]
They were kept only for emotional reasons, but they can be deleted now, since I printed and framed them already.

**Review by vandenman — APPROVED** [review]

**Comment by vandenman** [comment]
A nice thing about the new vdiffr framework is that these kinds of orphaned snapshots should be taken care of automatically.

**Pull request merged**
