### PR TITLE
DO NOT MERGE: Check whether unit tests work. Nothing happening other than printing stuff

### PR DESCRIPTION
**Pull request by AlexanderLyNL**

### CODE REVIEW

**Comment by AlexanderLyNL** [comment]
@JorisGoosen  Do you know what's going on with jaspResults on mac? 

This PR is based on the master branch and it shouldn't lead to it failing. The jaspTable has the right numbers, but some of these numbers are set to zero, see also 

https://github.com/jasp-stats/jaspRegression/pull/151#issuecomment-1218143606

**Comment by JorisGoosen** [comment]
Maybe this is caused by https://github.com/jasp-stats/jaspColumnEncoder/commit/81c1f70171f71913d7aa1eb2f65f9046db8bd337 (Ill check it again, I thought the code was correct but it sure looks messed up)

**Comment by JorisGoosen** [comment]
oooh yeah... I forgot an `abs(...)`

**Comment by JorisGoosen** [comment]
fixed it

**Comment by AlexanderLyNL** [comment]
Thanks! Solved by Joris. This PR was only to poke.

**Pull request closed without merging**
